# Generated by Django 2.2.6 on 2019-10-08 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='firstName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='lastName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='person',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='phonebook.Person'),
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('person', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='phonebook.Person')),
            ],
        ),
    ]
