# Generated by Django 2.2.6 on 2019-10-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0002_auto_20191008_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='firstName',
            field=models.CharField(max_length=50, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='person',
            name='lastName',
            field=models.CharField(max_length=50, verbose_name='Nazwisko'),
        ),
    ]
