# Generated by Django 2.2.6 on 2019-10-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0003_auto_20191010_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='number',
            field=models.CharField(max_length=50, verbose_name='Numer telefonu'),
        ),
    ]
